using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RestApi_WinForms_03._05;
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RestApi_03._05;
//
//    var adat = Adat.FromJson(jsonString);

namespace RestApi_WinForms_03._05
{

    public partial class Adat
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("salary")]
        public long Salary { get; set; }
    }

    public partial class Adat
    {
        public static Adat[] FromJson(string json) => JsonConvert.DeserializeObject<Adat[]>(json, RestApi_WinForms_03._05.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Adat[] self) => JsonConvert.SerializeObject(self, RestApi_WinForms_03._05.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
